In [1]:
# Bootsrap 

import sys, os
sys.path.insert(0, os.path.abspath(".."))

%load_ext autoreload
%autoreload 2

import pandas as pd
import numpy as np
from src.config import DATA_PROCESSED, OUTPUT_TABLES

# Load cleaned datasets
meps = pd.read_csv(DATA_PROCESSED / "meps_diabetes_2023_clean.csv")
brfss = pd.read_csv(DATA_PROCESSED / "brfss_diabetes_2023_clean.csv")

print(f"MEPS analytic sample : {len(meps):,} rows × {len(meps.columns)} cols")
print(f"BRFSS analytic sample: {len(brfss):,} rows × {len(brfss.columns)} cols")

MEPS analytic sample : 812 rows × 34 cols
BRFSS analytic sample: 1,983 rows × 43 cols

In [2]:
# MEPS Table A 
from src.descriptive_tables import build_table_a, build_table_b, save_table, MEPS_VARS, BRFSS_VARS

meps_table_a = build_table_a(meps, MEPS_VARS, dataset_label="MEPS HC-251 (2023)")

# Save and preview
out_path = OUTPUT_TABLES / "meps_table_a_all_sample.xlsx"
save_table(meps_table_a, out_path, sheet_name="All-sample (n=812)")
print(f"Saved: {out_path}")

meps_table_a

Saved: /Users/ht/Desktop/aly6150_diabetes_project/aly6150-diabetes-health-project/outputs/tables/meps_table_a_all_sample.xlsx

,Variable,Category,N (valid),Statistic,Missing %
0,Total medical expense ($),median (IQR),812,"8,642 (2,072–19,741)",0.0%
1,Out-of-pocket spending ($),median (IQR),812,424.5 (82.8–1463.0),0.0%
2,Prescription spending ($),median (IQR),812,"2,811 (288–9,194)",0.0%
3,High spender (top 25%),Yes,812,203 (25.0%),0.0%
4,Any ER visit,Yes,812,211 (26.0%),0.0%
5,Any inpatient stay,Yes,812,105 (12.9%),0.0%
6,Age (years),median (IQR),812,57.0 (52.0–61.0),0.0%
7,Age band,45-54,812,290 (35.7%),0.0%
8,,55-64,812,522 (64.3%),
9,Sex,Female,812,417 (51.4%),0.0%
10,,Male,812,395 (48.6%),
11,Race / ethnicity,Hispanic,812,203 (25.0%),0.0%
12,,NH Asian,812,45 (5.5%),
13,,NH Black,812,177 (21.8%),
14,,NH Other/Multiple,812,23 (2.8%),
15,,NH White,812,364 (44.8%),
16,Insurance coverage,Any private,812,459 (56.5%),0.0%
17,,Public only,812,292 (36.0%),
18,,Uninsured,812,61 (7.5%),
19,Poverty tier,High Income (400%+),812,251 (30.9%),0.0%
20,,Low Income (125-199%),812,118 (14.5%),
21,,Middle Income (200-399%),812,231 (28.4%),
22,,Near Poor (100-124%),812,45 (5.5%),
23,,Poor (<100% FPL),812,167 (20.6%),
24,<200% FPL,Yes,812,330 (40.6%),0.0%
25,Northeast region,Yes,812,98 (12.1%),0.0%
26,Comorbidity count (0-4),median (IQR),809,2.0 (1.0–2.0),0.4%

In [4]:
# BRFSS Table A 

brfss_table_a = build_table_a(brfss, BRFSS_VARS, dataset_label="BRFSS LLCP2023 (NE)")

out_path = OUTPUT_TABLES / "brfss_table_a_all_sample.xlsx"
save_table(brfss_table_a, out_path, sheet_name="All-sample (n=1983)")
print(f"Saved: {out_path}")

brfss_table_a

Saved: /Users/ht/Desktop/aly6150_diabetes_project/aly6150-diabetes-health-project/outputs/tables/brfss_table_a_all_sample.xlsx

,Variable,Category,N (valid),Statistic,Missing %
0,Missed care due to cost,Yes,1977,178 (9.0%),0.3%
1,Uninsured,Yes,1911,54 (2.8%),3.6%
2,Has personal doctor,Yes,1968,"1,914 (97.3%)",0.8%
3,Recent (past-year) checkup,Yes,1973,"1,856 (94.1%)",0.5%
4,Age band,45-54,1983,616 (31.1%),0.0%
5,,55-64,1983,"1,367 (68.9%)",
6,Sex,Female,1983,939 (47.4%),0.0%
7,,Male,1983,"1,044 (52.6%)",
8,Race / ethnicity,AI/AN,1983,22 (1.1%),0.0%
9,,Hispanic,1983,190 (9.6%),
10,,NH Asian,1983,40 (2.0%),
11,,NH Black,1983,94 (4.7%),
12,,NH White,1983,"1,571 (79.2%)",
13,,Other/Multiple,1983,66 (3.3%),
14,Education,College grad,1973,654 (33.1%),0.5%
15,,Grades 1-8,1973,59 (3.0%),
16,,Grades 9-11,1973,97 (4.9%),
17,,HS/GED,1973,605 (30.7%),
18,,No school/K only,1973,3 (0.2%),
19,,Some college,1973,555 (28.1%),
20,Income tier,$25-50K,1650,383 (23.2%),16.8%
21,,$50-75K,1650,424 (25.7%),
22,,$75K+,1650,451 (27.3%),
23,,<$25K,1650,392 (23.8%),
24,Low income (<$50K),Yes,1650,590 (35.8%),16.8%
25,Obese (BMI ≥30),Yes,1800,"1,082 (60.1%)",9.2%
26,Current smoker,Yes,1880,336 (17.9%),5.2%
27,Meets PA guideline,Yes,1652,784 (47.5%),16.7%
28,Fair/poor self-rated health,Yes,1978,833 (42.1%),0.3%
29,Comorbidity count (0-8),median (IQR),1983,2.0 (1.0–3.0),0.0%
30,Takes insulin,Yes,722,246 (34.1%),63.6%
31,Days physical health not good,median (IQR),1921,2.0 (0.0–20.0),3.1%
32,Days mental health not good,median (IQR),1944,1.0 (0.0–10.0),2.0%

In [5]:
# BRFSS Table B (by state):
brfss_table_b = build_table_b(
    brfss,
    BRFSS_VARS,
    group_col="state_name",
    group_label="State",
    dataset_label="BRFSS LLCP2023 (NE)",
)

out_path = OUTPUT_TABLES / "brfss_table_b_by_state.xlsx"
save_table(brfss_table_b, out_path, sheet_name="By state")
print(f"Saved: {out_path}")

brfss_table_b

Saved: /Users/ht/Desktop/aly6150_diabetes_project/aly6150-diabetes-health-project/outputs/tables/brfss_table_b_by_state.xlsx

,Variable,Category,Overall,State: Connecticut,State: Maine,State: Massachusetts,State: New Hampshire,State: Rhode Island,State: Vermont,Test,p-value
0,,(n),"1,983",399,504,335,224,270,251,,
1,Missed care due to cost,Yes,178 (9.0%),34 (8.5%),35 (7.0%),34 (10.1%),26 (11.7%),34 (12.6%),15 (6.0%),Chi-square,0.035
2,Uninsured,Yes,54 (2.8%),15 (3.9%),13 (2.7%),6 (1.8%),6 (2.8%),8 (3.1%),6 (2.5%),Chi-square,0.675
3,Has personal doctor,Yes,"1,914 (97.3%)",378 (96.2%),494 (98.4%),324 (98.2%),222 (99.6%),252 (93.3%),244 (97.6%),Chi-square,<0.001
4,Recent (past-year) checkup,Yes,"1,856 (94.1%)",374 (94.4%),476 (95.0%),312 (93.4%),208 (92.9%),255 (95.1%),231 (92.4%),Chi-square,0.616
5,Age band,45-54,616 (31.1%),131 (32.8%),150 (29.8%),123 (36.7%),50 (22.3%),86 (31.9%),76 (30.3%),Chi-square,0.015
6,,55-64,"1,367 (68.9%)",268 (67.2%),354 (70.2%),212 (63.3%),174 (77.7%),184 (68.1%),175 (69.7%),,
7,Sex,Female,939 (47.4%),181 (45.4%),260 (51.6%),141 (42.1%),100 (44.6%),136 (50.4%),121 (48.2%),Chi-square,0.084
8,,Male,"1,044 (52.6%)",218 (54.6%),244 (48.4%),194 (57.9%),124 (55.4%),134 (49.6%),130 (51.8%),,
9,Race / ethnicity,AI/AN,22 (1.1%),2 (0.5%),9 (1.8%),3 (0.9%),1 (0.4%),1 (0.4%),6 (2.4%),Chi-square,<0.001
10,,Hispanic,190 (9.6%),67 (16.8%),9 (1.8%),50 (14.9%),3 (1.3%),55 (20.4%),6 (2.4%),,
11,,NH Asian,40 (2.0%),16 (4.0%),3 (0.6%),14 (4.2%),1 (0.4%),4 (1.5%),2 (0.8%),,
12,,NH Black,94 (4.7%),36 (9.0%),4 (0.8%),33 (9.9%),2 (0.9%),16 (5.9%),3 (1.2%),,
13,,NH White,"1,571 (79.2%)",270 (67.7%),459 (91.1%),225 (67.2%),211 (94.2%),183 (67.8%),223 (88.8%),,
14,,Other/Multiple,66 (3.3%),8 (2.0%),20 (4.0%),10 (3.0%),6 (2.7%),11 (4.1%),11 (4.4%),,
15,Education,College grad,654 (33.1%),142 (35.8%),140 (27.8%),140 (42.0%),79 (35.4%),73 (27.5%),80 (31.9%),Chi-square,<0.001
16,,Grades 1-8,59 (3.0%),18 (4.5%),3 (0.6%),10 (3.0%),5 (2.2%),22 (8.3%),1 (0.4%),,
17,,Grades 9-11,97 (4.9%),12 (3.0%),19 (3.8%),19 (5.7%),16 (7.2%),24 (9.1%),7 (2.8%),,
18,,HS/GED,605 (30.7%),120 (30.2%),183 (36.3%),83 (24.9%),77 (34.5%),66 (24.9%),76 (30.3%),,
19,,No school/K only,3 (0.2%),0 (0.0%),1 (0.2%),1 (0.3%),0 (0.0%),0 (0.0%),1 (0.4%),,
20,,Some college,555 (28.1%),105 (26.4%),158 (31.3%),80 (24.0%),46 (20.6%),80 (30.2%),86 (34.3%),,
21,Income tier,$25-50K,383 (23.2%),87 (26.8%),120 (28.0%),48 (18.1%),38 (20.8%),50 (21.6%),40 (18.3%),Chi-square,<0.001
22,,$50-75K,424 (25.7%),63 (19.4%),120 (28.0%),59 (22.3%),50 (27.3%),49 (21.2%),83 (38.1%),,
23,,$75K+,451 (27.3%),117 (36.0%),70 (16.4%),86 (32.5%),60 (32.8%),61 (26.4%),57 (26.1%),,
24,,<$25K,392 (23.8%),58 (17.8%),118 (27.6%),72 (27.2%),35 (19.1%),71 (30.7%),38 (17.4%),,
25,Low income (<$50K),Yes,590 (35.8%),103 (31.7%),180 (42.1%),98 (37.0%),54 (29.5%),99 (42.9%),56 (25.7%),Chi-square,<0.001
26,Obese (BMI ≥30),Yes,"1,082 (60.1%)",198 (56.4%),294 (61.9%),174 (56.3%),134 (68.4%),132 (55.0%),150 (65.5%),Chi-square,0.009
27,Current smoker,Yes,336 (17.9%),57 (15.5%),89 (18.5%),62 (19.5%),26 (12.2%),46 (18.3%),56 (22.7%),Chi-square,0.058
28,Meets PA guideline,Yes,784 (47.5%),140 (42.0%),201 (47.4%),142 (50.7%),85 (46.2%),104 (47.1%),112 (53.3%),Chi-square,0.148
29,Fair/poor self-rated health,Yes,833 (42.1%),170 (42.8%),239 (47.4%),135 (40.5%),85 (38.1%),108 (40.0%),96 (38.2%),Chi-square,0.083
30,Comorbidity count (0-8),median (IQR),2.0 (1.0–3.0),2.0 (1.0–3.0),3.0 (2.0–4.0),2.0 (1.0–3.0),2.0 (1.0–3.0),2.0 (1.0–3.0),2.0 (1.0–3.0),Kruskal-Wallis,<0.001
31,Takes insulin,Yes,246 (34.1%),—,172 (34.4%),—,74 (33.3%),—,—,Chi-square,0.846
32,Days physical health not good,median (IQR),2.0 (0.0–20.0),2.0 (0.0–15.0),4.0 (0.0–25.0),3.0 (0.0–21.0),2.0 (0.0–15.0),2.0 (0.0–15.0),2.0 (0.0–14.0),Kruskal-Wallis,0.026
33,Days mental health not good,median (IQR),1.0 (0.0–10.0),0.0 (0.0–10.0),2.0 (0.0–15.0),1.0 (0.0–15.0),0.0 (0.0–10.0),0.0 (0.0–8.0),2.0 (0.0–10.0),Kruskal-Wallis,0.029

In [7]:
# BRFSS diabetes self-management module — only ran in Maine and New Hampshire
# This is a sub-table for the ~676 respondents who answered these questions.

from src.descriptive_tables import (
    BRFSS_DIABETES_MODULE_VARS,
    brfss_diabetes_module_subset,
)

brfss_module = brfss_diabetes_module_subset(brfss)
print(f"Diabetes-module subset: {len(brfss_module):,} respondents (ME + NH only)")

brfss_module_table = build_table_a(
    brfss_module,
    BRFSS_DIABETES_MODULE_VARS,
    dataset_label="BRFSS LLCP2023 — Diabetes self-management module",
)

# Also stratify by state since we have only two states here
brfss_module_by_state = build_table_b(
    brfss_module,
    BRFSS_DIABETES_MODULE_VARS,
    group_col="state_name",
    group_label="State",
    dataset_label="BRFSS LLCP2023 — Diabetes self-management module",
)

out_path_a = OUTPUT_TABLES / "brfss_module_table_a.xlsx"
out_path_b = OUTPUT_TABLES / "brfss_module_table_b_by_state.xlsx"
save_table(brfss_module_table, out_path_a, sheet_name="ME+NH module (n=676)")
save_table(brfss_module_by_state, out_path_b, sheet_name="ME vs NH")
print(f"Saved: {out_path_a}")
print(f"Saved: {out_path_b}")

brfss_module_table

Diabetes-module subset: 676 respondents (ME + NH only)
Saved: /Users/ht/Desktop/aly6150_diabetes_project/aly6150-diabetes-health-project/outputs/tables/brfss_module_table_a.xlsx
Saved: /Users/ht/Desktop/aly6150_diabetes_project/aly6150-diabetes-health-project/outputs/tables/brfss_module_table_b_by_state.xlsx

,Variable,Category,N (valid),Statistic,Missing %
0,Takes insulin,Yes,674,233 (34.6%),0.3%
1,Recent A1C check (past year),Yes,676,655 (96.9%),0.0%
2,Recent dilated eye exam,Yes,676,133 (19.7%),0.0%
3,Preventive care index (0-2),median (IQR),676,1.0 (1.0–1.0),0.0%

In [8]:
brfss_module_by_state

,Variable,Category,Overall,State: Maine,State: New Hampshire,Test,p-value
0,,(n),676,465,211,,
1,Takes insulin,Yes,233 (34.6%),159 (34.3%),74 (35.1%),Chi-square,0.922
2,Recent A1C check (past year),Yes,655 (96.9%),450 (96.8%),205 (97.2%),Chi-square,0.979
3,Recent dilated eye exam,Yes,133 (19.7%),95 (20.4%),38 (18.0%),Chi-square,0.529
4,Preventive care index (0-2),median (IQR),1.0 (1.0–1.0),1.0 (1.0–1.0),1.0 (1.0–1.0),Mann-Whitney U,0.569

In [3]:
# MEPS Table B (by insurance type)

meps_table_b = build_table_b(
    meps,
    MEPS_VARS,
    group_col="insurance_label",
    group_label="Insurance",
    dataset_label="MEPS HC-251 (2023)",
)

out_path = OUTPUT_TABLES / "meps_table_b_by_insurance.xlsx"
save_table(meps_table_b, out_path, sheet_name="By insurance type")
print(f"Saved: {out_path}")

meps_table_b

Saved: /Users/ht/Desktop/aly6150_diabetes_project/aly6150-diabetes-health-project/outputs/tables/meps_table_b_by_insurance.xlsx

,Variable,Category,Overall,Insurance: Any private,Insurance: Public only,Insurance: Uninsured,Test,p-value
0,,(n),812,459,292,61,,
1,Total medical expense ($),median (IQR),"8,642 (2,072–19,741)","8,425 (2,205–18,600)","12,066 (4,038–23,930)",519.0 (48.0–3238.0),Kruskal-Wallis,<0.001
2,Out-of-pocket spending ($),median (IQR),424.5 (82.8–1463.0),743.0 (228.0–2046.5),121.5 (13.8–664.5),264.0 (17.0–672.0),Kruskal-Wallis,<0.001
3,Prescription spending ($),median (IQR),"2,811 (288–9,194)","2,758 (286–8,648)","4,685 (676–12,486)",84.0 (7.0–545.0),Kruskal-Wallis,<0.001
4,High spender (top 25%),Yes,203 (25.0%),105 (22.9%),96 (32.9%),2 (3.3%),Chi-square,<0.001
5,Any ER visit,Yes,211 (26.0%),90 (19.6%),109 (37.3%),12 (19.7%),Chi-square,<0.001
6,Any inpatient stay,Yes,105 (12.9%),50 (10.9%),49 (16.8%),6 (9.8%),Chi-square,0.048
7,Age (years),median (IQR),57.0 (52.0–61.0),57.0 (52.0–60.0),58.0 (53.0–61.2),56.0 (52.0–60.0),Kruskal-Wallis,0.006
8,Age band,45-54,290 (35.7%),177 (38.6%),89 (30.5%),24 (39.3%),Chi-square,0.065
9,,55-64,522 (64.3%),282 (61.4%),203 (69.5%),37 (60.7%),,
10,Sex,Female,417 (51.4%),223 (48.6%),164 (56.2%),30 (49.2%),Chi-square,0.121
11,,Male,395 (48.6%),236 (51.4%),128 (43.8%),31 (50.8%),,
12,Race / ethnicity,Hispanic,203 (25.0%),95 (20.7%),76 (26.0%),32 (52.5%),Chi-square,<0.001
13,,NH Asian,45 (5.5%),37 (8.1%),7 (2.4%),1 (1.6%),,
14,,NH Black,177 (21.8%),85 (18.5%),80 (27.4%),12 (19.7%),,
15,,NH Other/Multiple,23 (2.8%),10 (2.2%),12 (4.1%),1 (1.6%),,
16,,NH White,364 (44.8%),232 (50.5%),117 (40.1%),15 (24.6%),,
17,Poverty tier,High Income (400%+),251 (30.9%),219 (47.7%),18 (6.2%),14 (23.0%),Chi-square,<0.001
18,,Low Income (125-199%),118 (14.5%),43 (9.4%),64 (21.9%),11 (18.0%),,
19,,Middle Income (200-399%),231 (28.4%),160 (34.9%),55 (18.8%),16 (26.2%),,
20,,Near Poor (100-124%),45 (5.5%),14 (3.1%),28 (9.6%),3 (4.9%),,
21,,Poor (<100% FPL),167 (20.6%),23 (5.0%),127 (43.5%),17 (27.9%),,
22,<200% FPL,Yes,330 (40.6%),80 (17.4%),219 (75.0%),31 (50.8%),Chi-square,<0.001
23,Northeast region,Yes,98 (12.1%),64 (13.9%),29 (9.9%),5 (8.2%),Chi-square,0.162
24,Comorbidity count (0-4),median (IQR),2.0 (1.0–2.0),2.0 (1.0–2.0),2.0 (1.0–2.0),2.0 (1.0–2.0),Kruskal-Wallis,<0.001

In [9]:
# MEPS Table C: stratified by high_spender 

# Table C — MEPS, stratified by high_spender flag (top 25% vs. bottom 75%)
# This sets up the predictive question: who are the top spenders, and how
# do they differ from everyone else?

# We need a labeled version of the high_spender flag for nicer column headers
meps_for_table_c = meps.copy()
meps_for_table_c["spender_group"] = meps_for_table_c["high_spender"].map({
    0: "Bottom 75%",
    1: "Top 25%",
})

# Build a variable spec that excludes high_spender itself (it's the grouping var)
# and the dollar variables (since high_spender is defined from total_medical_expense,
# including it would be circular for the test). Keep them in for descriptive
# context but they will look mechanically extreme.
from src.descriptive_tables import MEPS_VARS

# Filter out the variables that would be circular / uninformative as predictors
MEPS_TABLE_C_VARS = {
    k: v for k, v in MEPS_VARS.items()
    if k != "high_spender"  # the grouping variable
}

meps_table_c = build_table_b(
    meps_for_table_c,
    MEPS_TABLE_C_VARS,
    group_col="spender_group",
    group_label="Spender group",
    dataset_label="MEPS HC-251 (2023) — by spender group",
)

out_path = OUTPUT_TABLES / "meps_table_c_by_spender.xlsx"
save_table(meps_table_c, out_path, sheet_name="By spender group")
print(f"Saved: {out_path}")

meps_table_c

Saved: /Users/ht/Desktop/aly6150_diabetes_project/aly6150-diabetes-health-project/outputs/tables/meps_table_c_by_spender.xlsx

,Variable,Category,Overall,Spender group: Bottom 75%,Spender group: Top 25%,Test,p-value
0,,(n),812,609,203,,
1,Total medical expense ($),median (IQR),"8,642 (2,072–19,741)","4,941 (1,173–10,908)","35,437 (25,487–59,733)",Mann-Whitney U,<0.001
2,Out-of-pocket spending ($),median (IQR),424.5 (82.8–1463.0),345.0 (56.0–1095.0),"1,084 (174–3,242)",Mann-Whitney U,<0.001
3,Prescription spending ($),median (IQR),"2,811 (288–9,194)","1,112 (161–5,979)","14,591 (4,582–24,202)",Mann-Whitney U,<0.001
4,Any ER visit,Yes,211 (26.0%),116 (19.0%),95 (46.8%),Chi-square,<0.001
5,Any inpatient stay,Yes,105 (12.9%),35 (5.7%),70 (34.5%),Chi-square,<0.001
6,Age (years),median (IQR),57.0 (52.0–61.0),57.0 (52.0–61.0),58.0 (53.0–61.0),Mann-Whitney U,0.455
7,Age band,45-54,290 (35.7%),227 (37.3%),63 (31.0%),Chi-square,0.128
8,,55-64,522 (64.3%),382 (62.7%),140 (69.0%),,
9,Sex,Female,417 (51.4%),298 (48.9%),119 (58.6%),Chi-square,0.021
10,,Male,395 (48.6%),311 (51.1%),84 (41.4%),,
11,Race / ethnicity,Hispanic,203 (25.0%),171 (28.1%),32 (15.8%),Chi-square,0.001
12,,NH Asian,45 (5.5%),38 (6.2%),7 (3.4%),,
13,,NH Black,177 (21.8%),131 (21.5%),46 (22.7%),,
14,,NH Other/Multiple,23 (2.8%),15 (2.5%),8 (3.9%),,
15,,NH White,364 (44.8%),254 (41.7%),110 (54.2%),,
16,Insurance coverage,Any private,459 (56.5%),354 (58.1%),105 (51.7%),Chi-square,<0.001
17,,Public only,292 (36.0%),196 (32.2%),96 (47.3%),,
18,,Uninsured,61 (7.5%),59 (9.7%),2 (1.0%),,
19,Poverty tier,High Income (400%+),251 (30.9%),197 (32.3%),54 (26.6%),Chi-square,0.013
20,,Low Income (125-199%),118 (14.5%),92 (15.1%),26 (12.8%),,
21,,Middle Income (200-399%),231 (28.4%),180 (29.6%),51 (25.1%),,
22,,Near Poor (100-124%),45 (5.5%),28 (4.6%),17 (8.4%),,
23,,Poor (<100% FPL),167 (20.6%),112 (18.4%),55 (27.1%),,
24,<200% FPL,Yes,330 (40.6%),232 (38.1%),98 (48.3%),Chi-square,0.013
25,Comorbidity count (0-4),median (IQR),2.0 (1.0–2.0),2.0 (1.0–2.0),2.0 (1.0–2.0),Mann-Whitney U,<0.001

In [6]:
# Spot check of the outcome-exposure relationship

# Does insurance type predict total medical spending (MEPS)?
# Does uninsured status predict missed care (BRFSS)?

print("=" * 60)
print("OUTCOME–EXPOSURE SPOT CHECKS")
print("=" * 60)

# MEPS: median total expense by insurance type
print("\nMEPS — Median total medical expense by insurance type:")
print(meps.groupby("insurance_label")["total_medical_expense"].agg(["count", "median", "mean"]).round(0).to_string())

# BRFSS: missed care rate by uninsured status
print("\nBRFSS — Missed-care-cost rate by insurance status:")
print(brfss.groupby("uninsured")["missed_care_cost"].agg(["count", "mean"]).round(3).to_string())
print("  (uninsured: 0 = covered, 1 = uninsured)")

============================================================
OUTCOME–EXPOSURE SPOT CHECKS
============================================================

MEPS — Median total medical expense by insurance type:
                 count   median     mean
insurance_label
Any private        459   8425.0  17835.0
Public only        292  12066.0  21590.0
Uninsured           61    519.0   3142.0

BRFSS — Missed-care-cost rate by insurance status:
           count   mean
uninsured
0.0         1851  0.078
1.0           54  0.481
  (uninsured: 0 = covered, 1 = uninsured)

In [10]:
# Save CSV versions of each table for downstream use
# (Python visualizations, Excel sharing, etc.)
from src.config import OUTPUT_TABLES

tables_to_export = {
    "meps_table_a_all_sample":       meps_table_a,
    "meps_table_b_by_insurance":     meps_table_b,
    "meps_table_c_by_spender":       meps_table_c,
    "brfss_table_a_all_sample":      brfss_table_a,
    "brfss_table_b_by_state":        brfss_table_b,
    "brfss_module_table_a":          brfss_module_table,
    "brfss_module_table_b_by_state": brfss_module_by_state,
}

for name, table in tables_to_export.items():
    csv_path = OUTPUT_TABLES / f"{name}.csv"
    table.to_csv(csv_path, index=False)
    print(f"Saved CSV: {csv_path.name}")

print(f"\n{len(tables_to_export)} table CSVs saved to: {OUTPUT_TABLES}")

Saved CSV: meps_table_a_all_sample.csv
Saved CSV: meps_table_b_by_insurance.csv
Saved CSV: meps_table_c_by_spender.csv
Saved CSV: brfss_table_a_all_sample.csv
Saved CSV: brfss_table_b_by_state.csv
Saved CSV: brfss_module_table_a.csv
Saved CSV: brfss_module_table_b_by_state.csv

7 table CSVs saved to: /Users/ht/Desktop/aly6150_diabetes_project/aly6150-diabetes-health-project/outputs/tables